# This workflow runs the Tenant Hunter Python script directly on GitHub's servers.

name: Run Tenant Hunter

# Configured to run on manual trigger
on:
  workflow_dispatch:

jobs:
  run-tenant-hunter:
    # Use the latest Ubuntu environment for a Linux-based runner
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        # Action to check out your code from the repository
        uses: actions/checkout@v4

      - name: Set up Python
        # Action to set up a specific Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        # Install the required libraries from your requirements.txt file
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create API Key Files
        # Create the config.json and service_account.json files from GitHub Secrets
        # This keeps your sensitive information secure and out of the public repository
        run: |
          python -c "import json; print(json.dumps({'GEMINI_API_KEY': '${{ secrets.GEMINI_API_KEY }}', 'YELP_API_KEY': '${{ secrets.YELP_API_KEY }}'}))" > config.json
          echo '${{ secrets.GOOGLE_SHEET_CREDS }}' > service_account.json

      - name: Run Tenant Hunter Script
        # This is the core step that executes your main Python file
        run: python tenant_hunter.py
