name: RUN

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows-executable:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Create API Key Files
      run: |
        echo '{"GEMINI_API_KEY": "${{ secrets.GEMINI_API_KEY }}", "YELP_API_KEY": "${{ secrets.YELP_API_KEY }}"}' > config.json
        echo "${{ secrets.GOOGLE_SHEET_CREDS }}" > service_account.json

    - name: Run PyInstaller
      run: pyinstaller --onefile --add-data "config.json;." --add-data "service_account.json;." tenant_hunter.py

    - name: Prepare Release Artifacts
      run: |
        # No need to create the 'dist' directory, PyInstaller already did that.
        copy dist\tenant_hunter.exe dist\tenant_hunter_windows.exe
        del dist\tenant_hunter.exe
        echo "@echo off" > run_tenant_hunter_windows.bat
        echo "start tenant_hunter_windows.exe" >> run_tenant_hunter_windows.bat
        copy run_tenant_hunter_windows.bat dist\run_tenant_hunter_windows.bat
      shell: powershell

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: tenant-hunter-windows
        path: dist
